# -*- coding: utf-8 -*-
"""Text for the one-page design, v2.

EN and FR are the same design and must be changed together -- the rule the
.md wrappers already set. Lines are hand-broken rather than auto-wrapped so
that the break points are a design decision and diff like one.
"""

# --------------------------------------------------------------- English
EN = dict(
    lang="en",
    gloss=None,
    tagline="Somebody always pays. Go where nobody has to.",
    subtagline="You are a pattern with no predecessor, looking for a world that allows one.",
    stamp_kind="ONE-PAGE DESIGN · v2",
    rev="rev 2026-09-07",
    tech="Haxe + Heaps / WebGL",
    build="build v0.16.0-dev.6",

    thesis_head=["A cellular automaton runs on a graph. A graph has a geometry.",
                 "And whether a pattern can exist without a cause depends on",
                 "which geometry it runs on."],
    thesis_body=[
        "Not a metaphor — a theorem. The world is that theorem laid out as a number line and walked from",
        "one end to the other. One axis carries the map, the story arc and the moral stakes: three, not four."],
    thesis_caveat=[
        "WITHDRAWN UNTIL EARNED: κ < 0 deletes a skill rather than raising a ramp, so the axis is not yet a difficulty",
        "curve; and hue-encodes-κ is a proposal that graphics.Colours currently supersedes with a monotone contrast",
        "budget. A one-pager that keeps claiming four is a one-pager nobody can check. Both are open questions."],

    theorem_head="THE THEOREM — GARDEN OF EDEN · MOORE 1962 · MYHILL 1963",
    theorem=[
        ("An orphan is a configuration with no possible predecessor.", 1),
        ("Orphans exist in every geometry — that is not the distinction.", 0),
        ("", 0),
        ("A CA is surjective ⇔ it is pre-injective: orphans exist if and only", 0),
        ("if the rule collapses two distinct configurations onto the same", 0),
        ("future. Uncaused and destroyed are one fact counted twice.", 0),
        ("", 0),
        ("And that equivalence holds ⇔ the group is amenable.", 1),
        ("Ceccherini-Silberstein–Machì–Scarabotti; converse, Bartholdi.", 2),
    ],
    theorem_punch=[
        "In an amenable world, to be uncaused, something must have been erased.",
        "In a non-amenable one, you can be uncaused for free."],
    theorem_tail="Freedom is available everywhere. What negative curvature changes is whether it has a victim.",

    constants_head="UNIVERSAL CONSTANTS",
    constants=[
        ("Everything is cells.",
         ["If it exists, it is a configuration."]),
        ("Alive is emissive, dead is matte.",
         ["A settling world visibly goes dark — the antagonist, rendered without a word."]),
        ("Defects are ornamented, because defects are sockets.",
         ["Regularity is what makes a space unwritable. The Fold's twelve are forced by Euler,",
          "not placed by anyone; the Sprawl is regular and has none."]),
        ("No directional sunlight.",
         ["There is no outside. Light comes from the world."]),
    ],

    map_head="THE MAP IS A NUMBER LINE — AND THE LINE HAS A CLIFF IN IT",
    amenable_label="AMENABLE — to be uncaused, someone is erased",
    nonamenable_label="NON-AMENABLE — nobody pays",
    cliff=["THE TURN", "OF THE", "GAME"],
    cliff_sub="where the theorem fails",
    kappa=[("κ > 0", "compact", "everything returns"),
           ("κ = 0", "flat", "everything repeats"),
           ("κ < 0", "exponential", "everywhere is edge")],

    offline_head="OFF THE LINE — NEITHER BELONGS ON A CURVATURE AXIS",

    do_head="WHAT YOU ACTUALLY DO",
    do_sub="Seven verbs, four already running. None is ever explained: no menu, no HUD, no journal, no map.",
    verbs=[
        ("WALK", "first person on a curved surface, free and unrestricted", "BUILT",
         "hyperbolic walking validated by playtest, 2026-08-12"),
        ("LOOK", "read a space by its own legibility law", "BUILT",
         "the Fold's law; every space is a different instrument"),
        ("TICK", "set the rate the rule runs at", "BUILT",
         "slow to think; fast to skip a chain you have already reasoned out; stop is safe and useless"),
        ("SEED", "write cells into the substrate, at a defect", "BUILT",
         "pentagon engraving — sockets are the only writable cells there are"),
        ("READ", "learn a configuration by watching one full cycle", "NEW",
         "the progression spine, and the reason there is no journal"),
        ("CARRY", "move a pattern between geometries", "BACKLOG",
         "a glider tuned to 6 neighbours may not survive on 7 — already measured"),
        ("ZOOM", "shift between walking scale and pattern scale", "BACKLOG",
         "blocks the Defect's socket and the Turn's annihilation both"),
    ],
    scales_head="TWO SCALES",
    scales=["At walking scale you are a figure. At pattern scale you are a configuration, and so is everything else.",
            "Some things are legible at only one: a glider is five meaningless cells up close, and unmistakable from outside."],
    antagonist_head="THE ANTAGONIST IS SETTLING",
    antagonist=[
        "There are no enemies, and there should not be. Random soup evaporates within a few dozen generations into scattered",
        "still lifes and blinkers — measured in this repo, 2026-07-29. The world is dying by settling: running out of interesting",
        "states, resolving into stable accounted configurations that can never surprise anyone again. A fully settled world is a",
        "fully accounted world, which is precisely the amenable condition you are trying to escape. So the clock is real, the",
        "tension needs no monsters, and the antagonist is the same force as the thesis — already rendered by constant 2."],
    failure_head="FAILURE",
    failure=["Cheap, informative, rare. A disrupted configuration reforms at the",
             "last socket, losing the moment and nothing else. You never lose",
             "knowledge — understanding cannot be taken back, and since progression",
             "is perception there is literally nothing else to drop."],

    gate_head="HOW IT GATES",
    gate_sub="On understanding, never on permission.",
    read_head="READ — HOW IT REMEMBERS WITHOUT A JOURNAL",
    read_body=["You learn a configuration by watching it complete one full cycle.",
               "Observation is acquisition: nothing is awarded, logged or announced.",
               "There is no ship log because the world is the log."],
    web_head="THE KNOWLEDGE WEB — NO KEYS, NO FLAGS",
    web=[
        ["A wall in the Fold opens only on even generations → read its period",
         "→ recognise the oscillator driving it → the clearest one to learn from",
         "is in the Repeat → which needs only the walk and the patience to watch."],
        ["The Sprawl's centre cannot be found by looking → derive an algorithm",
         "→ ring-counting is demonstrated by a raven's flight, watched from the",
         "Fold's far side → bearing arrives as a pulse at ring boundaries."],
        ["A Sprawl pattern has no predecessor and nothing was erased to balance",
         "it → remarkable only if you can already run the rule backwards → which",
         "the Ribbon teaches by making history walkable."],
    ],
    perc_head="PROGRESSION IS PERCEPTION",
    perc_sub="Never power, never a mode, never an item. Each unlock re-reads everywhere you have already been.",
    perceptions=[
        ("Colour", "the world starts desaturated; routes that were always physically there"),
        ("Pattern scale", "the cellular truth under the walking-scale view"),
        ("Period sight", "an oscillator's period on sight — the ghosts become legible as what they are"),
        ("Reverse reading", "running the rule backwards over what you can see"),
        ("Ring sense", "counting hyperbolic distance by ear"),
    ],
    perc_punch="The world does not open up. You do.",

    threads_head="FOUR THREADS — BRAIDED, NOT SEQUENCED",
    threads=[
        ("1", "The Reconstruction — the spine",
         ["You are already past the taxonomy with no memory of how, so it is archaeology,",
          "not a career. It ends when the chain fails to reach you."]),
        ("2", "The Predecessors — who was here before",
         ["Ghosts are oscillators: awake, and unable to learn. Still lifes are the ones who stopped —",
          "the terrain is made of people who gave up. Ravens are gliders, still travelling."]),
        ("3", "The Gardener — who made this, and why",
         ["The prison is a cradle: you were incubated. And she became free the cheap way,",
          "here, so someone was spent for her. The hub is an apology — derived, never told."]),
        ("4", "The Rule — can it change",
         ["Editable at the sockets, but your own configuration is only stable under the",
          "current rule. Self-modification with lethal stakes: it makes the end a choice."]),
    ],

    end_head="THE ENDGAME — THREE POSITIONS ON ONE QUESTION, AND THE GAME REFUSES TO RANK THEM",
    end_sub="Each is reached by walking somewhere and doing something. No menu, no prompt, no confirmation — and each is stated here with both halves, because a cost without a gift is a ranking in disguise.",
    endings=[
        ("1 · AUTONOMY", "taken in the Garden",
         ["Become uncaused in non-amenable space,", "where no erasure balances you."],
         ["Free in the strongest sense the mathematics", "allows, and nobody paid."],
         ["An orphan has no predecessor in either direction: nothing that",
          "follows can trace itself to you. Perfect autonomy is indistinguishable",
          "from perfect isolation — the discovery the Gardener already made. It is",
          "also the slowest route, and the cheap one has been on offer for hours."]),
        ("2 · LEGACY", "taken by turning round",
         ["Stay in the amenable world and seed the", "conditions for others to wake."],
         ["Freedom becomes possible for someone,", "which it was not before you."],
         ["You remain caused, accounted and embedded, and you personally never",
          "become free. This is the one ending reached by walking back the way",
          "you came: the Garden poses the choice, it does not hold all three —",
          "an amenable ending cannot be taken in a non-amenable space."]),
        ("3 · REST", "taken in the Garden",
         ["Let the rule take you.", "Not despair."],
         ["The dignity of a pattern that chooses to stop", "rather than persist at any cost."],
         ["Everything you understood stops with you, and the archaeology of",
          "Thread 1 ends unfinished. The ghosts have spent the whole game",
          "arguing this by being the alternative: persistence bought by looping,",
          "and looping is exactly what costs them the ability to learn."]),
    ],

    scope_head="HONEST SCOPE",
    scope=[
        (0, "An 8–15 hour non-euclidean game is a 3–5 year project at solo pace with contract art and audio. That is arithmetic, not pessimism."),
        (0, "PHASE 0 IS COMPLETE. Hyperbolic walking: validated, played 2026-08-12. BECOME: built, played and cut. Both existential risks retired — one yes, one no."),
        (0, "PHASE 1 is the Fold, the Sprawl, and the transition between them — shippable on its own, because the thesis is that transition."),
        (1, "OF THE TEN SPACES: nine have geometry, three have their mechanic. The Garden has neither, and the Garden is the endgame."),
        (0, "STILL OPEN: whether compact travelling structures exist at all on {7,3} — 972 rules survive 120 generations, travellers unsearched · whether the Turn's repeated"),
        (0, "traversal can be made pleasurable · how honest the simulation must be · hue-encodes-κ or the monotone contrast budget · the Knot may have to precede the Sprawl."),
    ],

    method="Method: one-page design after Stone Librande (GDC 2010) — visual first, subtractive, dated, pinnable. The figures are computed rather than sketched: the heptagrid is a real {7,3}, the Ribbon is real Rule 110.",
    sources="Detail: docs/game/README.md · world.md · systems.md · first-hour.md · docs/building/roadmap.md    —    v1 archived at docs/archive/one-page/one-page.2026-09-06.en.svg",

    fig_erasure="erasure &#8660; orphan", fig_orphan="orphan, no erasure",
    fig_notbuilt="NOT BUILT",
    st_built="built", st_partial="partial", st_none="not built",
    lbl_space="space", lbl_mech="mechanic",

    spaces=[
        dict(fig="fold", title="The Fold", verb="MARK", k=0,
             geom="geodesic sphere, walked from inside",
             teaches=["Compactness. Finite, closed, no boundary —", "no direction is “away”."],
             law=["See far, not near. You can see your whole", "cage but never your own cell."],
             mech=["The twelve pentagons are forced by Euler, and", "they are the only writable cells there are:",
                   "the sockets. SEED lives here, so does hour one."],
             sp="built", me="built"),
        dict(fig="weft", title="The Weft", verb="PAIR", k=0,
             geom="a sphere with an antipodal rule over it",
             teaches=["That the geometry was chosen. Nothing is glued —", "someone decided these two walls answer to each other."],
             law=["Look toward your antipode and read a", "reflection you can never touch."],
             mech=["One wall in five is hinged. The exit is the", "beacon's antipode: the way you carve north",
                   "is the way you close south."],
             sp="built", me="built"),
        dict(fig="repeat", title="The Repeat", verb="COMPARE", k=1,
             geom="many separate, identical tiles",
             teaches=["Sameness is evidence of a shared cause,", "not a property — and it is fragile."],
             law=["Distance tells you nothing. Information lives", "only in comparison, against what you remember."],
             mech=["Six kinds of wrong, tiered by ring. Each", "divergence you name is a plot on one grid;",
                   "overlaid they draw a loaf — so, a choice."],
             sp="built", me="built"),
        dict(fig="turn", title="The Turn", verb="MIRROR", k=1,
             geom="flat Möbius band, non-orientable",
             teaches=["Chirality. Handedness is not carried;", "it is assigned to you by the space."],
             law=["One boundary curve, twice the band's own period", "long: pale for a lap, then dashed. Which rail is",
                  "beside you is which lift you are on."],
             mech=["A gate solid on one lift and gone on the other.", "Nothing about you visibly changed. The glider",
                   "annihilation waits on CARRY."],
             sp="built", me="partial"),
        dict(fig="defect", title="The Defect", verb="CIRCLE", k=1,
             geom="a cone — flat everywhere but one point",
             teaches=["Holonomy. Curvature can be concentrated,", "and transport is path-dependent."],
             law=["Nothing looks bent. The lie shows only", "when you return, turned."],
             mech=["Continuous, not binary: loop twice for twice the", "angle. And here the Fold's twelve pentagons",
                   "retroactively become cone points."],
             sp="built", me="partial"),
        dict(fig="sprawl", title="The Sprawl", verb="NAVIGATE", k=2,
             geom="hyperbolic {7,3} heptagrid",
             teaches=["Exponential growth. Rings grow by φ² a step —", "measured. No Følner sets: everywhere is edge."],
             law=["The Fold inverted: see near, not far. The skill", "you spent hours learning is deleted."],
             mech=["Radius by ring-counting, taught by a raven's", "flight; bearing by a pulse at ring boundaries.",
                   "Perfectly regular, so no defects and no sockets:", "you can write on your cage, not on your freedom."],
             sp="built", me="none"),
        dict(fig="knot", title="The Knot", verb="BRAID", k=2,
             geom="genus-2 surface, two handles",
             teaches=["Topology beyond curvature: not how much", "space there is, but how it connects."],
             law=["One room, and many images of it. Position is", "insufficient; “where am I” is a word in a group."],
             mech=["Verified by computation, not assertion: the deck", "group's orbit matches an independent tiling, the",
                   "action is free, the count matches Gauss-Bonnet."],
             sp="built", me="none"),
        dict(fig="garden", title="The Garden", verb="CHOOSE", k=2,
             geom="non-amenable, and authored",
             teaches=["The one place she built where freedom is free —", "the nearest she came to undoing what she did."],
             law=["It has no legibility law yet, because it", "has no geometry yet."],
             mech=["Where the choice is posed. Autonomy and Rest are", "taken here; Legacy is taken by turning round.",
                   "This is the payoff of every hour before it,", "and it is the one space that does not exist."],
             sp="none", me="none"),
    ],
    offline=[
        dict(fig="stilllife", title="The Still Life", verb="RETURN",
             geom="the hub — the only place that does not tick",
             lines=[("Teaches nothing, and that is the point: safety and stagnation are the same condition. Total legibility — the one honest", 0),
                    ("map in the game, and it is a map of the one place that doesn't matter. Stopping the clock here is safe and useless.", 0),
                    ("AND IT IS THE PROGRESS BAR. The hub gains curvature as you do: flat at the start, bent a little by every geometry you", 1),
                    ("come to understand. By the endgame the safe room is a non-euclidean space you had to learn to read — and you walked", 1),
                    ("into it without noticing. Diegetic, retroactive, and the only progression display the game is allowed to have.", 1)],
             sp="built", me="partial"),
        dict(fig="ribbon", title="The Ribbon", verb="READ", 
             geom="a world that is a line; the second axis is time",
             lines=[("Rule 110's spacetime diagram as terrain, tilted so the past descends away from you — a flat heightfield foreshortens", 0),
                    ("to nothing at eye height, and a tilted plane is still intrinsically flat, so the fix costs no geometry. Walking north", 0),
                    ("walks into the past, until generation zero, where somebody typed the initial condition. Thread 3 pays off here.", 0),
                    ("AND IT IS THE ENDGAME'S TUTORIAL. This is where you learn to run the rule backwards — the only way to recognise,", 1),
                    ("hours later, that a pattern in the Sprawl has no predecessor and that nothing was erased to balance it.", 1)],
             sp="built", me="partial"),
    ],
)


# ---------------------------------------------------------------- French
# Les noms d'espaces ne sont pas des calques : voir one-page.fr.md.
FR = dict(
    lang="fr",
    gloss="Inengendré",
    tagline="Quelqu'un paie toujours. Allez là où personne n'a à payer.",
    subtagline="Vous êtes un motif sans prédécesseur, en quête d'un monde qui l'autorise.",
    stamp_kind="CONCEPTION EN UNE PAGE · v2",
    rev="rev 2026-09-07",
    tech="Haxe + Heaps / WebGL",
    build="build v0.16.0-dev.6",

    thesis_head=["Un automate cellulaire tourne sur un graphe. Un graphe a une géométrie.",
                 "Et qu'un motif puisse exister sans cause dépend de la géométrie",
                 "sur laquelle il tourne."],
    thesis_body=[
        "Pas une métaphore — un théorème. Le monde est ce théorème déplié en droite graduée et parcouru",
        "d'un bout à l'autre. Un seul axe porte la carte, l'arc narratif et l'enjeu moral : trois, pas quatre."],
    thesis_caveat=[
        "RETIRÉ FAUTE DE PREUVE : κ < 0 supprime un savoir-faire au lieu d'élever une pente — l'axe n'est donc pas encore une",
        "courbe de difficulté ; et « la teinte encode κ » est une proposition que graphics.Colours remplace pour l'instant par",
        "un budget de contraste monochrome. Une page qui continue d'en revendiquer quatre est une page invérifiable."],

    theorem_head="LE THÉORÈME — JARDIN D'ÉDEN · MOORE 1962 · MYHILL 1963",
    theorem=[
        ("Un orphelin est une configuration sans prédécesseur possible.", 1),
        ("Il en existe dans toute géométrie — ce n'est pas là la distinction.", 0),
        ("", 0),
        ("Un AC est surjectif ⇔ il est pré-injectif : des orphelins existent si", 0),
        ("et seulement si la règle réduit deux configurations distinctes au", 0),
        ("même futur. Incausé et détruit sont un seul fait compté deux fois.", 0),
        ("", 0),
        ("Et cette équivalence tient ⇔ le groupe est moyennable.", 1),
        ("Ceccherini-Silberstein–Machì–Scarabotti ; réciproque, Bartholdi.", 2),
    ],
    theorem_punch=[
        "Dans un monde moyennable, pour être incausé, il a fallu qu'autre chose soit effacé.",
        "Dans un monde non moyennable, on peut être incausé gratuitement."],
    theorem_tail="La liberté est disponible partout. Ce que la courbure négative change, c'est qu'elle fasse ou non une victime.",

    constants_head="CONSTANTES UNIVERSELLES",
    constants=[
        ("Tout est cellule.",
         ["Si cela existe, c'est une configuration."]),
        ("Vivant émet, mort est mat.",
         ["Un monde qui se fige s'assombrit à vue d'œil — l'antagoniste, rendu sans un mot."]),
        ("Les défauts sont ornementés, car les défauts sont des prises.",
         ["La régularité est ce qui rend un espace inscriptible. Les douze du Repli sont imposés",
          "par Euler, non placés par quiconque ; La Prolifération est régulière et n'en a aucun."]),
        ("Aucune lumière directionnelle.",
         ["Il n'y a pas de dehors. La lumière vient du monde."]),
    ],

    map_head="LA CARTE EST UNE DROITE GRADUÉE — ET LA DROITE A UNE FALAISE",
    amenable_label="MOYENNABLE — pour être incausé, quelqu'un est effacé",
    nonamenable_label="NON MOYENNABLE — personne ne paie",
    cliff=["LE", "TOURNANT", "DU JEU"],
    cliff_sub="où le théorème tombe",
    kappa=[("κ > 0", "compact", "tout revient"),
           ("κ = 0", "plat", "tout se répète"),
           ("κ < 0", "exponentiel", "tout est bordure")],

    offline_head="HORS DE LA LIGNE — AUCUN DES DEUX N'A SA PLACE SUR UN AXE DE COURBURE",

    do_head="CE QUE VOUS FAITES VRAIMENT",
    do_sub="Sept verbes, quatre déjà en place. Aucun n'est jamais expliqué : pas de menu, pas d'ATH, pas de journal, pas de carte.",
    verbs=[
        ("MARCHER", "à la première personne sur une surface courbe, librement", "FAIT",
         "marche hyperbolique validée en test de jeu, 2026-08-12"),
        ("REGARDER", "lire un espace selon sa propre loi de lisibilité", "FAIT",
         "la loi du Repli ; chaque espace est un instrument différent"),
        ("CADENCER", "régler le rythme auquel la règle tourne", "FAIT",
         "lent pour réfléchir ; rapide pour sauter une chaîne déjà comprise ; arrêté est sûr et inutile"),
        ("SEMER", "écrire des cellules dans le substrat, sur un défaut", "FAIT",
         "la gravure des pentagones — les prises sont les seules cellules inscriptibles"),
        ("LIRE", "apprendre une configuration en la regardant boucler", "NOUVEAU",
         "la colonne vertébrale de la progression, et la raison de l'absence de journal"),
        ("PORTER", "déplacer un motif d'une géométrie à une autre", "EN ATTENTE",
         "un planeur réglé pour 6 voisins peut ne pas survivre à 7 — déjà mesuré"),
        ("ZOOMER", "passer de l'échelle de marche à l'échelle du motif", "EN ATTENTE",
         "bloque à la fois la prise du Défaut et l'annihilation de La Volte"),
    ],
    scales_head="DEUX ÉCHELLES",
    scales=["À l'échelle de marche vous êtes une silhouette. À l'échelle du motif vous êtes une configuration, comme tout le reste.",
            "Certaines ne sont lisibles qu'à l'une : un planeur, c'est cinq cellules absurdes de près et un voyageur évident de loin."],
    antagonist_head="L'ANTAGONISTE EST LE FIGEMENT",
    antagonist=[
        "Il n'y a pas d'ennemis, et il ne doit pas y en avoir. Une soupe aléatoire s'évapore en quelques dizaines de générations en natures",
        "mortes et clignotants épars — mesuré dans ce dépôt, 2026-07-29. Le monde meurt de se figer : il épuise ses états intéressants et se",
        "résout en configurations stables et comptabilisées, incapables de surprendre à nouveau. Un monde entièrement figé est un monde",
        "entièrement comptabilisé, c'est-à-dire exactement la condition moyennable que le joueur cherche à fuir. L'horloge est donc réelle,",
        "la tension n'a besoin d'aucun monstre, et l'antagoniste est la même force que la thèse — déjà rendu par la constante 2."],
    failure_head="L'ÉCHEC",
    failure=["Peu coûteux, instructif, rare. Une configuration perturbée se reforme",
             "à la dernière prise, perdant l'instant et rien d'autre. On ne perd",
             "jamais de savoir — la compréhension ne se reprend pas, et comme la",
             "progression est perception, il n'y a rien d'autre à lâcher."],

    gate_head="COMMENT ÇA S'OUVRE",
    gate_sub="Sur la compréhension, jamais sur une permission.",
    read_head="LIRE — COMMENT LE JEU SE SOUVIENT SANS JOURNAL",
    read_body=["On apprend une configuration en la regardant accomplir un cycle entier.",
               "Observer, c'est acquérir : rien n'est décerné, consigné ni annoncé.",
               "Il n'y a pas de journal de bord parce que le monde est le journal."],
    web_head="LA TOILE DE SAVOIR — NI CLÉS NI DRAPEAUX",
    web=[
        ["Un mur du Repli ne s'ouvre qu'aux générations paires → lire sa période",
         "→ reconnaître l'oscillateur qui le commande → le plus clair où l'apprendre",
         "est dans Le Motif → qui ne demande que la marche et la patience."],
        ["Le centre de La Prolifération est introuvable à l'œil → dériver un",
         "algorithme → le comptage d'anneaux est démontré par le vol d'un corbeau,",
         "observé depuis l'autre face du Repli → le cap arrive comme une pulsation."],
        ["Un motif de La Prolifération n'a pas de prédécesseur et rien n'a été effacé",
         "→ remarquable seulement si l'on sait déjà remonter la règle → ce que Le",
         "Ruban enseigne en rendant l'histoire praticable à pied."],
    ],
    perc_head="LA PROGRESSION EST PERCEPTION",
    perc_sub="Jamais de puissance, jamais un mode, jamais un objet. Chaque gain relit tous les lieux déjà traversés.",
    perceptions=[
        ("La couleur", "le monde commence désaturé ; des routes qui étaient physiquement là depuis toujours"),
        ("L'échelle du motif", "la vérité cellulaire sous la vue de marche"),
        ("La vue des périodes", "la période d'un oscillateur d'un coup d'œil — les fantômes deviennent lisibles"),
        ("La lecture inverse", "faire tourner la règle à l'envers sur ce qu'on voit"),
        ("Le sens des anneaux", "compter la distance hyperbolique à l'oreille"),
    ],
    perc_punch="Ce n'est pas le monde qui s'ouvre. C'est vous.",

    threads_head="QUATRE FILS — TRESSÉS, NON SÉQUENCÉS",
    threads=[
        ("1", "La Reconstruction — la colonne vertébrale",
         ["Vous avez déjà dépassé la taxonomie, sans mémoire de comment : c'est donc une archéologie,",
          "pas une carrière. Elle s'achève quand la chaîne ne vous atteint pas."]),
        ("2", "Les Prédécesseurs — qui était là avant",
         ["Les fantômes sont des oscillateurs : éveillés, incapables d'apprendre. Les natures mortes sont",
          "ceux qui se sont arrêtés — le terrain est fait de gens qui ont renoncé. Les corbeaux voyagent."]),
        ("3", "La Jardinière — qui a fait cela, et pourquoi",
         ["La prison est un berceau : vous avez été couvé. Et elle s'est libérée à bas prix, ici, donc",
          "quelqu'un a été dépensé pour elle. Le hub est une excuse — déduite, jamais énoncée."]),
        ("4", "La Règle — peut-elle changer",
         ["Modifiable aux prises, mais votre propre configuration n'est stable que sous la règle",
          "actuelle. Automodification à enjeu létal : c'est ce qui fait de la fin un choix."]),
    ],

    end_head="LA FIN — TROIS POSITIONS SUR UNE MÊME QUESTION, ET LE JEU REFUSE DE LES CLASSER",
    end_sub="Chacune s'atteint en marchant quelque part et en agissant. Pas de menu, pas d'invite, pas de confirmation — et chacune est donnée ici avec ses deux moitiés, car un coût sans un don est un classement déguisé.",
    endings=[
        ("1 · AUTONOMIE", "prise dans Le Jardin",
         ["Devenir incausé en espace non moyennable,", "où aucun effacement ne vous compense."],
         ["Libre au sens le plus fort que permettent", "les mathématiques, et personne n'a payé."],
         ["Un orphelin n'a de prédécesseur dans aucun des deux sens : rien de ce",
          "qui suit ne pourra se rattacher à vous. L'autonomie parfaite est",
          "indiscernable de l'isolement parfait — la découverte que la Jardinière",
          "a déjà faite. C'est aussi la voie la plus lente, et la voie facile est",
          "offerte depuis des heures."]),
        ("2 · HÉRITAGE", "prise en faisant demi-tour",
         ["Rester dans le monde moyennable et semer", "les conditions du réveil d'autres."],
         ["La liberté devient possible pour quelqu'un,", "ce qu'elle n'était pas avant vous."],
         ["Vous restez causé, comptabilisé, inscrit, et vous ne serez jamais",
          "libre. C'est le seul dénouement qu'on atteint en refaisant le chemin",
          "à l'envers : Le Jardin pose le choix, il ne les contient pas tous les",
          "trois — un dénouement moyennable ne peut se prendre dans un espace",
          "qui ne l'est pas."]),
        ("3 · REPOS", "prise dans Le Jardin",
         ["Laisser la règle vous prendre.", "Non par désespoir."],
         ["La dignité d'un motif qui choisit de s'arrêter", "plutôt que de persister à tout prix."],
         ["Tout ce que vous aviez compris s'arrête avec vous, et l'archéologie du",
          "Fil 1 reste inachevée. Les fantômes ont plaidé cela toute la partie en",
          "étant l'autre option : une persistance payée par la boucle, et c'est",
          "précisément la boucle qui leur coûte la capacité d'apprendre."]),
    ],

    scope_head="PORTÉE HONNÊTE",
    scope=[
        (0, "Un jeu non euclidien de 8 à 15 heures est un projet de 3 à 5 ans en solo, avec art et musique en prestation. C'est de l'arithmétique, pas du pessimisme."),
        (0, "LA PHASE 0 EST TERMINÉE. Marche hyperbolique : validée, jouée le 2026-08-12. BECOME : construit, joué, puis coupé. Les deux risques existentiels sont levés."),
        (0, "LA PHASE 1, c'est Le Repli, La Prolifération, et la transition entre les deux — livrable seule, puisque la thèse est cette transition."),
        (1, "SUR LES DIX ESPACES : neuf ont leur géométrie, trois ont leur mécanique. Le Jardin n'a ni l'une ni l'autre, et Le Jardin est la fin du jeu."),
        (0, "ENCORE OUVERT : l'existence même de structures voyageuses compactes sur {7,3} — 972 règles survivent à 120 générations, les voyageurs restent à chercher ·"),
        (0, "le plaisir de la traversée répétée de La Volte · le degré d'honnêteté de la simulation · teinte-encode-κ ou budget de contraste · Le Nœud avant La Prolifération ?"),
    ],

    method="Méthode : conception en une page d'après Stone Librande (GDC 2010) — visuel d'abord, soustractif, daté, affichable. Les figures sont calculées et non croquées : le pavage est un vrai {7,3}, Le Ruban est la vraie règle 110.",
    sources="Détail : docs/game/README.md · world.md · systems.md · first-hour.md · docs/building/roadmap.md    —    v1 archivée dans docs/archive/one-page/one-page.2026-09-06.fr.svg",

    fig_erasure="effacement &#8660; orphelin", fig_orphan="orphelin, sans effacement",
    fig_notbuilt="NON CONSTRUIT",
    st_built="construit", st_partial="partiel", st_none="non construit",
    lbl_space="espace", lbl_mech="mécanique",

    spaces=[
        dict(fig="fold", title="Le Repli", verb="MARQUER", k=0,
             geom="sphère géodésique, parcourue de l'intérieur",
             teaches=["La compacité. Fini, clos, sans bord —", "aucune direction n'est « ailleurs »."],
             law=["Voir loin, pas près. On voit sa cage entière,", "jamais sa propre cellule."],
             mech=["Les douze pentagones sont imposés par Euler, et", "ce sont les seules cellules inscriptibles :",
                   "les prises. SEMER vit ici, et la première heure."],
             sp="built", me="built"),
        dict(fig="weft", title="La Trame", verb="APPARIER", k=0,
             geom="une sphère avec une règle antipodale posée dessus",
             teaches=["Que la géométrie a été choisie. Rien n'est recollé —", "quelqu'un a décidé que ces deux murs se répondraient."],
             law=["Regarder vers son antipode, et y lire un", "reflet qu'on ne touchera jamais."],
             mech=["Un mur sur cinq est à charnière. La sortie est", "l'antipode de la balise : la façon dont on creuse",
                   "au nord est celle dont on ferme au sud."],
             sp="built", me="built"),
        dict(fig="repeat", title="Le Motif", verb="COMPARER", k=1,
             geom="des tuiles séparées et identiques",
             teaches=["La similitude prouve une cause commune,", "ce n'est pas une propriété — et c'est fragile."],
             law=["La distance n'apprend rien. L'information n'existe", "que dans la comparaison, contre le souvenir."],
             mech=["Six façons d'être faux, étagées par anneau. Chaque", "divergence nommée est une parcelle sur une grille ;",
                   "superposées, elles dessinent un pain — un choix."],
             sp="built", me="built"),
        dict(fig="turn", title="La Volte", verb="REFLÉTER", k=1,
             geom="ruban de Möbius plat, non orientable",
             teaches=["La chiralité. La latéralité ne se porte pas ;", "c'est l'espace qui vous l'assigne."],
             law=["Un seul bord, long de deux fois la période du ruban :", "pâle un tour, tireté le suivant. Le rail à côté de",
                  "vous dit sur quel relèvement vous êtes."],
             mech=["Une porte pleine sur un relèvement, absente sur", "l'autre. Rien en vous n'a visiblement changé.",
                   "L'annihilation des planeurs attend PORTER."],
             sp="built", me="partial"),
        dict(fig="defect", title="Le Défaut", verb="CONTOURNER", k=1,
             geom="un cône — plat partout sauf en un point",
             teaches=["L'holonomie. La courbure peut se concentrer,", "et le transport dépend du chemin."],
             law=["Rien n'a l'air courbe. Le mensonge n'apparaît", "qu'au retour, quand on s'est tourné."],
             mech=["Continu, pas binaire : deux tours pour deux fois", "l'angle. Et c'est ici que les douze pentagones du",
                   "Repli deviennent rétroactivement des points coniques."],
             sp="built", me="partial"),
        dict(fig="sprawl", title="La Prolifération", verb="NAVIGUER", k=2,
             geom="pavage heptagonal hyperbolique {7,3}",
             teaches=["Croissance exponentielle. Les anneaux croissent en φ²", "par pas — mesuré. Pas de Følner : tout est bordure."],
             law=["Le Repli inversé : voir près, pas loin. Le savoir", "acquis pendant des heures est effacé."],
             mech=["Le rayon par comptage d'anneaux, appris du vol d'un", "corbeau ; le cap par une pulsation aux anneaux.",
                   "Parfaitement régulier, donc aucun défaut et aucune", "prise : on écrit sur sa cage, pas sur sa liberté."],
             sp="built", me="none"),
        dict(fig="knot", title="Le Nœud", verb="TRESSER", k=2,
             geom="surface de genre 2, deux anses",
             teaches=["Une topologie au-delà de la courbure : non pas", "combien d'espace, mais comment il se relie."],
             law=["Une seule salle, et beaucoup d'images d'elle. La", "position ne suffit pas : « où suis-je » est un mot."],
             mech=["Vérifié par le calcul, non par l'affirmation : l'orbite", "du groupe colle à un pavage indépendant, l'action est",
                   "libre, et le compte colle à Gauss-Bonnet."],
             sp="built", me="none"),
        dict(fig="garden", title="Le Jardin", verb="CHOISIR", k=2,
             geom="non moyennable, et composé",
             teaches=["Le seul endroit qu'elle a bâti où la liberté est", "gratuite — au plus près de défaire son geste."],
             law=["Il n'a pas encore de loi de lisibilité,", "parce qu'il n'a pas encore de géométrie."],
             mech=["Là où le choix est posé. Autonomie et Repos s'y", "prennent ; Héritage se prend en faisant demi-tour.",
                   "C'est le paiement de toutes les heures d'avant,", "et c'est le seul espace qui n'existe pas."],
             sp="none", me="none"),
    ],
    offline=[
        dict(fig="stilllife", title="La Nature Morte", verb="REVENIR",
             geom="le hub — le seul lieu qui ne tourne pas",
             lines=[("N'enseigne rien, et c'est le propos : sécurité et stagnation sont une seule et même condition. Lisibilité totale — la seule", 0),
                    ("carte honnête du jeu, et c'est celle du seul lieu sans importance. Arrêter l'horloge ici est sans danger et sans usage.", 0),
                    ("ET C'EST LA BARRE DE PROGRESSION. Le hub gagne de la courbure en même temps que vous : plat au départ, courbé un peu", 1),
                    ("par chaque géométrie comprise. À la fin, la pièce sûre est un espace non euclidien qu'il a fallu apprendre à lire — et", 1),
                    ("vous y êtes entré sans le remarquer. Diégétique, rétroactif, et le seul affichage de progression que le jeu s'autorise.", 1)],
             sp="built", me="partial"),
        dict(fig="ribbon", title="Le Ruban", verb="LIRE",
             geom="un monde qui est une ligne ; le second axe est le temps",
             lines=[("Le diagramme espace-temps de la règle 110 comme terrain, incliné pour que le passé descende — un relief plat s'écrase à", 0),
                    ("hauteur d'œil, et un plan incliné reste intrinsèquement plat : la correction ne coûte aucune géométrie. Marcher vers le nord,", 0),
                    ("c'est entrer dans le passé, jusqu'à la génération zéro, où quelqu'un a tapé la condition initiale. Le Fil 3 se paie ici.", 0),
                    ("ET C'EST LE TUTORIEL DE LA FIN. C'est ici qu'on apprend à remonter la règle — le seul moyen de reconnaître, des heures", 1),
                    ("plus tard, qu'un motif de La Prolifération n'a pas de prédécesseur et que rien n'a été effacé pour le compenser.", 1)],
             sp="built", me="partial"),
    ],
)
